{% set name = "snowmappy" %}
{% set version = "1.0.2" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 554bc700a1fdff62e0a5d73300b09076a97859c8f9368c2da7e3f36932b7b980

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy ==2.1.0
    - scipy ==1.15.2
    - pandas ==2.2.3
    - setuptools ==75.1.0
    - pycrs ==1.0.2
    - rasterio ==1.4.3
    - rioxarray ==0.19.0
    - geopandas ==1.0.1
    - pyproj ==3.7.1
    - shapely ==2.1.0
    - affine ==2.4.0
    - xarray ==2025.3.1
    - zarr ==3.0.6
    - numcodecs ==0.16.0
    - h5py ==3.13.0
    - netCDF4 ==1.7.2
    - earthengine-api ==1.5.9
    - geemap ==0.35.3
    - xee ==0.0.20
    - tqdm ==4.66.4
    - joblib ==1.4.2
    - python-dateutil ==2.9.0

test:
  imports:
    - SnowMapPy
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/haytamelyo/SnowMapPy
  summary: "A Python package for processing MODIS NDSI data."
  description: |
    SnowMapPy is a Python package designed for hydrologists, geographers, and water resource managers. It simplifies snow cover analysis by processing MODIS NDSI data from local files and Google Earth Engine.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/haytamelyo/SnowMapPy#readme
  dev_url: https://github.com/haytamelyo/SnowMapPy

extra:
  recipe-maintainers:
    - haytamelyo
    - hbechri

# Ensure there is one empty line at the end of the file
